
module.exports = {
    encryptedData : "encryptedData",
    iv : "iv",
    OpenID : "OpenID",
    UnionID: "UnionID",
    js_code : 'js_code',
    SessionID : 'SessionID',
    UserID: 'UserID',
    CustomerID: 'CustomerID',
		ManagerID: 'ManagerID',
    StudentID: 'StudentID',
    TeacherID: 'TeacherID',
    OrganizationID: 'OrganizationID',
    GradeID: 'GradeID',
    SubjectID: 'SubjectID',
    Description: 'Description',
    UserNickName: 'UserNickName',
    Status: 'Status',
    Longitude: 'Longitude',
    Latitude: 'Latitude',
    RecordID: 'RecordID',
    UsingCar: "UsingCar",
    UsingCarStatus: "UsingCarStatus",
		UsingCarDevice: "UsingCarDevice",
		Level: "Level",
		PhoneNum: "PhoneNum",
		CatalogID: "CatalogID",
}